# ---------------------------------------------------------------------------------------------
# MIT License
# Copyright (c) 2022, Solace Corporation, Ricardo Gomez-Ulmke (ricardo.gomez-ulmke@solace.com)
# ---------------------------------------------------------------------------------------------

name: release
on:
  # for testing
  workflow_dispatch:
  # for production
  release:
    types: [created]
env:
  # DEBUG_FLAG: ${{ true }}
  DEBUG_FLAG: ${{ false }}
  IMPORTER_CLI_DIR: "ep-import"
  IMPORTER_CLI_TEST_LOGS_DIR: "ep-import/release/tmp/logs"
  IMPORTER_CLI_TEST_LOGS_OUTPUT_NAME: "ep-import-release-logs"
jobs:
  release:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 1
      matrix:
        node: [ '16' ]
    steps:
      - name: Check Auth
        if: github.event_name == 'workflow_dispatch' && github.actor != 'ricardojosegomezulmke'
        run: |
          echo "not authorized"
          echo '::set-output name=IS_AUTHORIZED::false'
        id: auth
      - name: Cancel Workflow
        if: ${{ always() && steps.auth.outputs.IS_AUTHORIZED == 'false' }}
        uses: andymckay/cancel-action@0.2

      - name: Checkout Current Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: env before install
        if: env.DEBUG_FLAG == 'true'
        run: |
          echo "bash --version: "; bash --version
          echo "node --version: "; node --version
          echo "npm --version: "; npm --version
          echo ">>> environment: TEST_* "
          env | grep TEST

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: env after install
        if: env.DEBUG_FLAG == 'true'
        run: |
          echo "bash --version: "; bash --version
          echo "node --version: "; node --version
          echo "npm --version: "; npm --version

      - name: "npm install"
        run: |
          cd "${IMPORTER_CLI_DIR}"
          npm install

      - name: "run release"
        run: |
          cd "${IMPORTER_CLI_DIR}"
          export CLI_SOLACE_CLOUD_TOKEN="${{ secrets.CLI_SOLACE_CLOUD_TOKEN }}"
          release/run.sh

      - name: Archive Importer Cli Release Logs
        if: ${{ (failure() && !cancelled()) || (always() && (github.event_name=='workflow_dispatch' || env.DEBUG_FLAG=='true') ) }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.IMPORTER_CLI_TEST_LOGS_OUTPUT_NAME }}
          path: ${{ github.workspace }}/${{ env.IMPORTER_CLI_TEST_LOGS_DIR }}
          if-no-files-found: error

###
# The End.
